/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class show_termbjava */

#ifndef _Included_show_termbjava
#define _Included_show_termbjava
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     show_termbjava
 * Method:    InitComm
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_show_termbjava_InitComm
  (JNIEnv *, jclass, jint);

/*
 * Class:     show_termbjava
 * Method:    CloseComm
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_show_termbjava_CloseComm
  (JNIEnv *, jclass);

/*
 * Class:     show_termbjava
 * Method:    Authenticate
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_show_termbjava_Authenticate
  (JNIEnv *, jclass);

/*
 * Class:     show_termbjava
 * Method:    Read_Content
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_show_termbjava_Read_1Content
  (JNIEnv *, jclass, jint);

/*
 * Class:     show_termbjava
 * Method:    Read_Content_Path
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_show_termbjava_Read_1Content_1Path
  (JNIEnv *, jclass, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
